kubernetes-sigs/cluster-api-operator

- OWNERS
- OWNERS_ALIASES
I added `cluster-api-operator-admins` alias and `sig-cluster-lifecycle-leads` to approvers, also removed @fabriziopandini see - https://github.com/kubernetes/org/issues/3119#issuecomment-985859765
> Update owners and aliases

- Makefile
- hack/cert-manager.sh
Add make the task for installing cert-manager. This makes operator development easier since it doesn't manage cert-manager lifecycle and has to be installed manually.
Fixes #
> 🌱  Add make task for installing cert manager

- OWNERS_ALIASES
In order to participate productively in the project, user Fedosin is required to be on the list of owners.
> 🌱 Add Fedosin to OWNERS

- api/v1alpha1/provider_types.go
- config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
Make version field required on API scheme level
this pr should go after https://github.com/kubernetes-sigs/cluster-api-operator/pull/29
/hold 
Fixes #
> 🐛Make version field required on API scheme level

- Tiltfile
- docs/local-development.md
This PR adds Tilt and documentation for setting up a local development environment.
> ✨ add local-development support using Tilt

- Makefile
- internal/controllers/component_customizer_test.go
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), projects within the Kubernetes orgs should update their image references to point to the new address.
**NOTE:** We can ignore references to staging-k8s.gcr.io, but any other references to k8s.gcr.io should be updated to registry.k8s.io
[k8s.gcr.io search results](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes-sigs/cluster-api-operator) 
ref: [[Umbrella Issue] Migrate K8s projects from k8s.gcr.io -> registry.k8s.io](https://github.com/kubernetes/k8s.io/issues/4738)
/kind cleanup
/priority important-soon
> 🌱 Update references from k8s.gcr.io to registry.k8s.io

- cloudbuild.yaml
Image builds are failing with a timeout https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-operator-push-images/1628085636898492416, I can see that other projects a bigger timeout value https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/cloudbuild.yaml#L2.
Fixes #
> 🌱 Increase cloudbuild timeout

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- controllers/alias.go
- internal/controllers/client_proxy.go
- internal/controllers/component_customizer.go
- internal/controllers/component_customizer_test.go
- internal/controllers/genericprovider_controller.go
- internal/controllers/genericprovider_controller_test.go
- internal/controllers/phases.go
- internal/controllers/phases_test.go
- internal/controllers/preflight_checks.go
- internal/envtest/environment.go
- internal/webhook/bootstrapprovider_webhook.go
- internal/webhook/controlplaneprovider_webhook.go
- internal/webhook/coreprovider_webhook.go
- internal/webhook/infrastructureprovider_webhook.go
- main.go
- util/util.go
To improve the code quality we enable additional golangci linters. Some desired linter are commented in `.golangci.yaml` file, but they will be enabled in the future.
> 🌱 Enable additional linters

- docs/capi-operator-proposal.md
- docs/getting-started.md
Update documentation for apiVersion values to `operator.cluster.x-k8s.io/v1alpha1`
> :book: Replace apiversion from management to operator

- go.mod
- internal/controllers/client_proxy.go
- internal/controllers/phases.go
- internal/controllers/preflight_checks.go
- internal/envtest/environment.go
This project is deprecated and not maintained anymore: https://github.com/pkg/errors
We can use standard golang primitives for that.
> 🌱 Stop using github.com/pkg/errors

- docs/getting-started.md
- docs/release.md
> 📖 Add helm chart to getting started doc

- Dockerfile
- Makefile
Current version 1.1 is outdated and not compatible with OCI:
```
docker pull docker.io/docker/dockerfile:1.1-experimental
Trying to pull docker.io/docker/dockerfile:1.1-experimental...
Error: copying system image from manifest list: initializing image from source docker://docker/dockerfile:1.1-experimental: unsupported docker v2s2 media type: "application/vnd.oci.image.layer.v1.tar+gzip"
```
To comply with cluster-api repo, we update it to v1.4.
> 🌱 Bump dockerfile image to v1.4

- Makefile
- scripts/ci-e2e.sh
- test/e2e/config/operator-dev.yaml
Currently we don't set defaults for 2 mandatory env variables: CERT_MANAGER_VERSION and OPERATOR_IMAGE. If user doesn't define them manually before running tests, the execution will fail with some vague error messages.
This commit ensures that the env variables always have default values.
> 🐛 fix: ensure that all required env variables are set before running tests

- internal/controller/genericprovider_controller_test.go
- internal/controller/phases.go
- internal/envtest/environment.go
Previously, the operator allowed only installation of new provider versions. Downgrading to a previous version would result in operator failure.
This PR introduces support for seamless provider downgrades in addition to upgrades.
> ✨ support provider downgrades

- internal/controller/genericprovider_controller_test.go
- internal/controller/phases.go
In the current implementation, when a provider version remains the same during subsequent reconciliations, the operator encounters an error with the message "failed getting clusterctl Provider version," leading to a degraded status.
This PR addresses this issue by adding a check to determine whether the provider version has changed or not.
Fixes #
> 🐛 Avoid failures on unchanged provider version

- internal/controller/consts.go
- internal/controller/phases.go
- internal/controller/phases_test.go
clusterctl [supports](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#creating-a-provider-repository-on-gitlab) provider installation from gitlab repositories, so we should implement it as well.
> ✨ support gitlab repos

- .golangci.yaml
- controllers/alias.go
- internal/controller/component_customizer_test.go
- internal/webhook/bootstrapprovider_webhook.go
- internal/webhook/controlplaneprovider_webhook.go
- internal/webhook/coreprovider_webhook.go
- internal/webhook/infrastructureprovider_webhook.go
Adds aliases for most common (k8s.io/*) and operator specific packages to make broader use of `importas` linter from the .golangci.yaml. Also, due to mandating of the imports, fixes some imports to pass the CI
> 🌱 Configure importas linter and fix import issues 

- internal/controller/preflight_checks.go
Currently if provider fails spec validation during preflight checks, we requeue it again with a 30 seconds interval. It doesn't make sense, because the spec still will be invalid and validation will fail again and again.
This PR identifies all places where we don't need to requeue providers and updates them accordingly.
> 🐛 Don't requeue provider if its spec is invalid

- test/e2e/helpers.go
- test/e2e/minimal_configuration.go
This PR adds several e2e tests to verify deletion, upgrading and downgrading providers.
> 🌱 add more e2e tests

- .gitignore
Signed-off by: Furkat Gofurov <furkat.gofurov@suse.com>
VSCode doesn't support nested modules and locally I am seeing few issues with it, i.e it will not give autocomplete or linting suggestions. Adding a go.work/go.sum files allows VSCode to recognize the nested modules.
> 🌱 Add go.work/go.sum to .gitignore

- Makefile
Passes `CGO=enabled` to building kustomize from tools folder to be able to build it within the container successfully
Fixes #132 
Related to: https://github.com/kubernetes-sigs/cluster-api/issues/8784
**Try it:**
```
$docker run -it --entrypoint /bin/bash gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20220609-2e4c91eb7e
bash-5.1# export CGO_ENABLED=0
bash-5.1# go install sigs.k8s.io/kustomize/kustomize/v5@v5.0.1
bash-5.1# which kustomize
/go/bin/kustomize
```
**Additional notes:**
Copy of https://github.com/kubernetes-sigs/cluster-api/pull/6231. All credits to @sbueringer 🎉
> 🐛 build: fix image push job by disabling CGO when building kustomize

- internal/controller/genericprovider/bootstrapprovider_wrapper.go
- internal/controller/genericprovider/controlplaneprovider_wrapper.go
- internal/controller/genericprovider/coreprovider_wrapper.go
- internal/controller/genericprovider/genericprovider_interfaces.go
- internal/controller/genericprovider/infrastructureprovider_wrapper.go
- internal/controller/genericprovider_controller.go
- internal/controller/manifests_downloader.go
- internal/controller/manifests_downloader_test.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/envtest/environment.go
Currently Cluster API Operator keeps refetching data from the specified URL after successful provider installation. It means that in case of network error Operator can't download manifests again and marks providers as unhealthy.
To prevent this, we fetch manifests only once in the beginning and store them in a configmap. For all the following reconciliations we take data from the configmap instead of downloading it from github/gitlab.
Fixes #119
> 🐛 Download and store manifests from provider URL

- api/v1alpha1/conditions_consts.go
- config/chart/manager_auth_proxy_patch.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- docs/getting-started.md
- go.mod
- go.sum
- internal/controller/phases.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
Validate github token in preflight checks
Fixes https://github.com/kubernetes-sigs/cluster-api-operator/issues/128
> ✨ Validate github token in preflight checks

- .golangci.yaml
- api/v1alpha1/provider_types.go
- cmd/main.go
- internal/controller/component_customizer.go
- internal/controller/component_customizer_test.go
- internal/controller/genericprovider/bootstrapprovider_wrapper.go
- internal/controller/genericprovider/controlplaneprovider_wrapper.go
- internal/controller/genericprovider/coreprovider_wrapper.go
- internal/controller/genericprovider/infrastructureprovider_wrapper.go
- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/phases.go
- internal/controller/preflight_checks_test.go
- internal/controller/suite_test.go
- internal/envtest/environment.go
- internal/webhook/bootstrapprovider_webhook.go
- internal/webhook/controlplaneprovider_webhook.go
- internal/webhook/coreprovider_webhook.go
- internal/webhook/infrastructureprovider_webhook.go
- webhook/alias.go
This PR enables additional linters and removes unused (commented) ones. All issues reported by linters are resolved either with "make lint-fix" or manually.
Noticeably, we fix implicit memory aliasing in for loops. In golang the iteration variable is reused. At each iteration, the value of the next element in the range expression is assigned to the iteration variable; "provider" doesn't change, only its value changes. Hence, the expression &provider is referring to the same location in memory.
The recommended solution for the issue is to redeclare "provider" inside the for loop.
For more information: https://github.com/golang/go/discussions/56010
> 🐛 Update linters and fix reported issues

- internal/controller/preflight_checks.go
Gosec linter reports a false error `G101: Potential hardcoded credentials (gosec)`. To prevent it we disable the linter in that place.
> 🐛 prevent false lint error

- internal/controller/manifests_downloader.go
- internal/controller/phases.go
Sometimes we use PreflightCheckCondition to report errors when preflight validations already passed, which is not correct. We need to use ProviderInstalledCondition in such cases.
Fixes #
> 🐛 use correct conditions for reporting errors after preflight checks

- internal/controller/component_customizer.go
**What this PR does / why we need it**: 
Now we call it only if Deployment spec is not empty. Then, inside the function, we customize both Deployment and Manager if related specs are not empty. It causes an error when we don't update Manager if Deployment spec is empty.
Fixes #172
> 🐛 Always call customizeDeployment function

- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/phases.go
Now we update provider components only if it's version has changed, but there are other cases where we need to do the same. For instance, when we update its DeploymentSpec or ManagementSpec.
Also we should reconcile providers if their spec is the same as for the last applied version. 
To fix it we calculate last applied spec hash and store it in a provider annotation. For next reconciliations we calculate the hash again. If it's the same as in the annotation, we skip further steps and stop immediately.
Fixes #156
> 🐛 Update provider components if (and only if) its spec has been changed

- api/v1alpha1/provider_types.go
- config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
- internal/controller/component_customizer.go
- internal/controller/component_customizer_test.go
Today, it's difficult to override the service account with an IRSA configured value. I would like the ability override the serviceAccountName for the deployment
Fixes #
> ✨ Add serviceAccountName to DeploymentSpec

- Makefile
- api/v1alpha1/provider_types.go
- config/chart/webhookcainjection_patch.yaml
- config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
- config/default/webhookcainjection_patch.yaml
- config/webhook/manifests.yaml
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/controller/preflight_checks.go
- internal/webhook/bootstrapprovider_webhook.go
- internal/webhook/controlplaneprovider_webhook.go
- internal/webhook/coreprovider_webhook.go
- internal/webhook/infrastructureprovider_webhook.go
- internal/webhook/provider_webhook.go
- internal/webhook/provider_webhook_test.go
Add the ability to specify a namespace for provider secret, this allows users to share a secret between providers. This way we can provide a better ux.
In the next version of API we can change the field to `corev1.ObjectReference`, I wanted to avoid a breaking change.
cc @damdo @Fedosin @furkatgofurov7 
Fixes #
> ✨  Add ability to specify a namespace for provider secret

- .github/workflows/golangci-lint.yml
- .github/workflows/release.yaml
- .golangci.yaml
- Dockerfile
- Makefile
- cmd/main.go
- go.mod
- hack/chart-update/go.mod
- hack/ensure-go.sh
- hack/tools/go.mod
- scripts/ci-verify.sh
Few CI jobs are failing in main branch ([e2e-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-operator-e2e-main/1679273348166586368), [test-main](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-operator/186/pull-cluster-api-operator-test-main/1679273348103671808)) and PRs like #186  due to go version incompatibility with k8s:
```
Activated service account credentials for: [prow-build@k8s-infra-prow-build.iam.gserviceaccount.com]
+ WRAPPED_COMMAND_PID=[2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-operator/186/pull-cluster-api-operator-test-main/1679273348103671808#1:build-log.txt%3A2)7
+ wait 27
+ ./scripts/ci-test.sh
Detected …
```
> ✨Bump go version to v1.20.4

- Dockerfile
Now we compile it twice, which seems unnecessary.
Fixes #
> 🌱 compile capi operator binary only once in the Dockerfile

- docs/README.md
- go.mod
- go.sum
- internal/controller/manifests_downloader.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- test/e2e/compressed_manifests_test.go
By default we download capi provider manifests from the provided URL and store it in a confimap to reuse later. Currently there is a limit on the configmap size, which is 1mb. If we the manifests size is bigger then the installation process fails.
To avoid it we will compress manifests if they can't be stored in the configmap directly.
Fixes #20
> 🐛 Compress components manifests if they don't fit in the configmap 

- go.mod
- go.sum
Bumps CAPI to latest https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.0 release
Fixes #194
> 🌱 Bump CAPI to v1.5.0

- Makefile
- cmd/plugin/cmd/root.go
- cmd/plugin/cmd/upgrade.go
- cmd/plugin/main.go
- go.mod
Add a clusterctl plugin module with a make task to build it. I didn't include it in the release process and no user documentation for now. The plugin can be compiled and used a standalone binary.
Fixes #
> ✨ Initialize operator clusterctl plugin

- test/e2e/compressed_manifests_test.go
Previously we added e2e tests to check situations when we have to compress data downloaded from an URL. But we also need to verify the operator behavior when we have an air-gapped environment, where providers are created from configmaps with compressed data.
Fixes #
> 🌱 add e2e tests for compressed manifests in air-gapped environments

- internal/controller/manifests_downloader.go
- internal/controller/phases.go
- test/e2e/compressed_manifests_test.go
Currently we do not support installation of providers with custom names for air-gapped environments. It happens because we inject new names in the list of known providers only for those with URL specified, ignoring config maps.
This PR fixes it, so we support both URL and ConfigMap installations with custom names.
Fixes #
> 🐛 Support installing providers with custom names in air-gapped environments

- api/v1alpha1/conditions_consts.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
When you try to install a Core Provider with a name different from "cluster-api", clusterctl validation [fails](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/providers_client.go#L414-L416).
After that CAPI operator puts a vague error description in the logs and doesn't add anything meaningful to the provider status.
This PR adds a pre-flight check to compare the Core Provider name with the expected name, allowing for earlier failure and an informative update to the provider status.
Fixes #
> 🌱 Add a preflight check to validate core provider name

- config/crd/kustomizeconfig.yaml
- test/e2e/resources/full-chart-install.yaml
Several paths for name references are not correct and therefore kustomize doesn't substitute right values there.
This PR fixes it and makes kustomize works correctly.
Reference patch: https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/config/crd/patches/webhook_in_coreproviders.yaml#L18
Fixes #
> 🐛 Fix incorrect fieldSpecs paths

- Makefile
- test/e2e/helm_test.go
- test/e2e/resources/full-chart-install.yaml
Addressing outstanding task in https://github.com/kubernetes-sigs/cluster-api-operator/pull/207#discussion_r1285722309
Fixes #
> 🐛 Add generate workflow for full-chart-install test case

- hack/charts/cluster-api-operator/templates/deployment.yaml
- hack/charts/cluster-api-operator/values.yaml
Based on https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#containers `imagePullSecrets` is part of the PodSpec, not ContainerSpec
This PR fix this bug by moving the `imagePullSecrets` to the right indentation, and also adjusts the values files accordingly.
Without this fix, the helm chart is not usable 😞 
Fixes #
Maybe a tool like https://github.com/yannh/kubeconform ran as a CI step might help in catching similar issues in the future
> 🐛 Fix imagePullSecrets bug

- .github/dependabot.yml
Now dependabot doesn't update dependencies for some modules, which which breaks consistency between them.
This PR enables dependabot for 3 remaining modules: `test`, `hack/tools` and `hack/chart-update`.
Fixes #
> 🌱 Add missing dependabot configs

- .github/dependabot.yml
Allow patch updates for the ignored dependencies in our dependabot config and group the k8s.io dependencies to reduce the number of individual PRs.
Inspired by: https://github.com/kubernetes-sigs/cluster-api/pull/9263
Fixes #
> 🌱 Add dependabot groups. Allow additional patch updates

- hack/charts/cluster-api-operator/templates/bootstrap-conditions.yaml
- hack/charts/cluster-api-operator/templates/bootstrap.yaml
- hack/charts/cluster-api-operator/templates/control-plane-conditions.yaml
- hack/charts/cluster-api-operator/templates/control-plane.yaml
- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra-conditions.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/helm_test.go
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-custom-versions.yaml
- test/e2e/resources/all-providers-latest-versions.yaml
- test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
- test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
- test/e2e/resources/multiple-infra-custom-ns-versions.yaml
- test/e2e/resources/only-bootstrap.yaml
- test/e2e/resources/only-control-plane.yaml
- test/e2e/resources/only-infra.yaml
We introduced v1alpha2 API in https://github.com/kubernetes-sigs/cluster-api-operator/pull/190. In this PR we update manifests in the helm chart to the new version.
Fixes #
> ⚠️ Use v1alpha2 manifests in the helm chart

- internal/controller/phases.go
Fixes bug with gitlab fetching.
url.RawPath is optional, and fulfilled only if provider 'fetchUrl' contains urlencoded characters.  It's better to use Url.Path
> :bug: Fix url fetch from gitlab repository

- hack/charts/cluster-api-operator/templates/deployment.yaml
Fix small typo in helm chart for leader election
related arguments
Related logs:
```
unknown flag: --leader-election-lease-duration
Usage of /manager:
...
--leader-elect-lease-duration duration   Interval at which non-leader candidates will wait to force acquire leadership (duration string) (default 15s)
--leader-elect-renew-deadline duration   Duration that the leading controller manager will retry refreshing leadership before giving up (duration string) (default 10s)
--leader-elect-retry-period duration     Duration the LeaderElector clients should wait between tries of actions (duration string) (default 2s)
...
```
Would be nice if we can get a new helm chart version released after it is merged (although not critical to have)
> :bug: Fix leader elect helm chart args

- docs/quickstart.md
Add quickstart to be embedded later in CAPI docs
Fixes #
> 📖 Add CAPI operator quickstart docs

- api/v1alpha2/conditions_consts.go
- cmd/main.go
- internal/controller/genericprovider_controller.go
- internal/controller/healthcheck/healthcheck_controller.go
- internal/controller/healthcheck/healthcheck_controller_test.go
- internal/controller/healthcheck/suite_test.go
Currently we don't check the provider health after its manifests are applied, and Provider controller sets `Installed` and `Ready` status conditions to `True` at the same time. It may be confusing for users, especially when provider startup fails - User sees the provider CR with condition Ready=True, but the deployment is not available.
To fix this we introduce Provider Health Check Controller, which will check the deployment and update Ready status condition accordingly.
Fixes #
> ✨ Add provider healthcheck controller

- docs/quickstart.md
Use absolute path to refer to operator installation from quickstart to be able to properly render it when referred to from the [CAPI book](https://main.cluster-api.sigs.k8s.io/user/quick-start-operator).
Also, removes highlighting of Hetzner provider in the reference link (I would assume it was typo and not intentional)
Note: currently link to "full documentation" in CAPI book refers to the doc in operator repo which can't be accessed and throws [not found error](https://main.cluster-api.sigs.k8s.io/user/README.html#installation), and we are replacing that with absolute path to make it possible to render it properly
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> 🐛 Use absolute path to refer to operator installation from quickstart

- OWNERS_ALIASES
Adding myself to the admins list mainly because I noticed this list will be used for kpromo image promotion PRs when releasing and tagging owners automatically in the [PR](https://github.com/kubernetes/k8s.io/pull/6081#issue-1994907757)
> 🌱 Add furkatgofurov7 to cluster-api-operator-admins list

- cmd/plugin/cmd/delete.go
- cmd/plugin/cmd/doc.go
- cmd/plugin/cmd/init.go
- cmd/plugin/cmd/move.go
- cmd/plugin/cmd/root.go
- cmd/plugin/cmd/upgrade.go
- cmd/plugin/cmd/upgrade_apply.go
- cmd/plugin/cmd/upgrade_plan.go
- cmd/plugin/cmd/utils.go
- cmd/plugin/cmd/version.go
- go.mod
- go.sum
This PR adds a skeleton for our plugin. It defines command line interfaces that will be used to manage CAPI providers, and additionally implements some utils to simplify working with the cluster.
Added interfaces for the next operations:
1. Init
2. Upgrade Plan
3. Upgrade Apply
4. Move
5. Delete
6. Version
Fixes #
> ✨ Add plugin skeleton

- .github/workflows/documentation.yaml
- docs/book/Makefile
- docs/book/book.toml
- docs/book/src/01_intro.md
- scripts/ci-install-mdbook.sh
> ✨ Add workflow for a book publishing job

- .github/workflows/release.yaml
- .goreleaser.yaml
- .krew.yaml
- Makefile
- docs/release.md
- hack/update-plugin-yaml.sh
```bash
clusterctl krew index add operator https://github.com/kubernetes-sigs/cluster-api-operator.git
clusterctl krew install operator/operator
clusterctl operator … # Is available
```
Fixes #328
> ✨ Allow clusterctl plugn to be installed with krew

- docs/book/Makefile
> :bug: Always add index.yaml to the book directory

- cmd/plugin/cmd/version.go
- hack/version.sh
- version/version.go
Now when we create capi operator binaries, we don't set ldflags correctly, despite the fact we should.
Example:
```sh
➭ make plugin  
go build -trimpath -ldflags "" -o bin/clusterctl-operator cmd/plugin/main.go
```
After the fix we get correct results:
```sh
➭ make plugin
go build -trimpath -ldflags "-X 'sigs.k8s.io/cluster-api-operator/version.buildDate=2023-12-05T13:32:09Z' -X 'sigs.k8s.io/cluster-api-operator/version.gitCommit=0e775448a54900148578f54ac9230bfe39535205' -X 'sigs.k8s.io/cluster-api-operator/version.gitTreeState=dirty' -X 'sigs.k8s.io/cluster-api-operator/version.gitMajor=0' -X 'sigs.k8s.io/cluster-api-operator/version.gitMinor=7' -X 'sigs.k8s.io/cluster-api-operator/version.gitVersion=v0.7.0-34-0e775448a54900-dirty' -X …
```
> 🐛 Fix version.sh script

- test/e2e/air_gapped_test.go
- test/e2e/minimal_configuration_test.go
Currently, e2e tests are failing because downgrade tests don't pass. I think it makes sense to not support downgrades in operator. Users can delete providers manually and recreate it with a smaller version, taking the risk of data loss because of CRD changes.
Fixes #
> 🌱 Remove downgrade e2e tests

- internal/controller/component_customizer.go
Healthcheck implementation expects deployment availability and an ownership reference pointing to the owner resource, to mark the provider as ready. However if the provider manifest is owned by some other resource, the second ownership reference appears on the deployment too, which is unexpected.
Fixes #350
> 🐛 Prevent propagation of OwnerReferences from provider manifests

- test/e2e/air_gapped_test.go
- test/e2e/e2e_suite_test.go
- test/go.mod
Now we don't delete CAPI CRDs when some e2e tests are over. It leads to a failure, when we have CAPI CRDs v1.6.0 and we want to install Core Provider v1.4.3.
To fix it we delete all the CRDs before running air-gapped tests.
Error message:
```
E1215 18:45:55.001141       1 controller.go:324]  "msg"="Reconciler error" "error"="action failed after 10 attempts: failed to patch provider object: CustomResourceDefinition.apiextensions.k8s.io \"ipaddressclaims.ipam.cluster.x-k8s.io\" is invalid: status.storedVersions[0]: Invalid value: \"v1beta1\": must appear in spec.versions" "CoreProvider"={"name":"cluster-api","namespace":"capi-operator-system"} "controller"="coreprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="CoreProvider" …
```
> 🐛 Delete all Cluster API CRDs before running air-gapped tests

- test/e2e/air_gapped_test.go
- test/e2e/compressed_manifests_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/helm_test.go
- test/e2e/helpers_test.go
- test/e2e/minimal_configuration_test.go
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-custom-versions.yaml
- test/e2e/resources/core-cluster-api-v1.5.4.yaml
- test/e2e/resources/core-cluster-api-v1.6.0.yaml
- test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
- test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
- test/e2e/resources/multiple-infra-custom-ns-versions.yaml
> ✨ Add artefacts collection after running e2e suite

- Makefile
- hack/cert-manager.sh
CAPI v1.6.0 uses cert-manager v1.13.2: https://github.com/kubernetes-sigs/cluster-api/pull/9653. CAPI operator should do the same.
Fixes #
> 🌱 Bump cert-manager version to v1.13.2

- internal/controller/consts.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/controller/preflight_checks.go
This allows to pass a default clusterctl.yaml file to the operator to fetch provider list from.
The file should be located under `/config/clusterctl.yaml`.
Fixes #
> ✨Allow to utilize providers from clusterctl.yaml file in /config/clusterctl.yaml

- internal/controller/component_customizer.go
- internal/controller/component_customizer_test.go
If there are several deployments in the manifest file, operator tries to apply provider changes to all of them, which leads to a failure.
In order to prevent this, we will customize only deployments with "cluster.x-k8s.io/provider" label.
Fixes #388
> 🐛 Customize only provider deployments

- internal/controller/component_customizer.go
- internal/controller/component_customizer_test.go
To prevent customization of non-manager deployments, we introduce a check that first verifies if there are several deployments. If there are several deployments available, we customize only those with names like "ca*-controller-manager" and skip the others.
Fixes #
> 🐛 don't customize non-manager deployments

- cmd/plugin/cmd/init.go
- cmd/plugin/cmd/init_test.go
- cmd/plugin/cmd/root.go
- cmd/plugin/cmd/suite_test.go
- cmd/plugin/cmd/utils.go
- go.mod
- internal/controller/consts.go
- internal/controller/manifests_downloader.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/envtest/environment.go
- test/testdata/cert-manager.crds.yaml
- util/util.go
This PR adds Init subcommand to the operator plugin.
Fixes #
> ✨ Implement Init plugin subcommand

- api/v1alpha2/conditions_consts.go
- internal/controller/client_proxy.go
- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/manifests_downloader.go
- internal/controller/phases.go
This would execute a correct upgrade procedure when a Provider version changes.
Fixes: https://github.com/kubernetes-sigs/cluster-api-operator/issues/404
Fixes #
> ✨ Execute provider upgrades when a version changes

- api/v1alpha2/conditions_consts.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
Cluster API doesn't support provider downgrades due to potential breaking changes in CRDs. Currently, if users try to downgrade for example from v1.6.1 to v1.5.2, they get a error:
```
invalid provider metadata: version v1.6.1 (the current version) for the provider capi-system/cluster-api does not match any release series
```
This is not really informative, so it is better to add a preflight check to fail earlier and provide more descriptive error messages.
Fixes #
> ✨ Add a preflight check to prevent provider downgrades

- .goreleaser.yaml
- With 1.24 release of goreleaser, we can move to a more cleaner approach of getting git state. 
Ref: https://github.com/goreleaser/goreleaser/commit/1ba3138c679cbd7f330e19d88adaae20c4a32eee
Fixes #
> 🌱 update git state syntax to goreleaser 1.24

- test/e2e/minimal_configuration_test.go
Release [v0.1.0](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/tag/v0.1.0) doesn't contain all required CRDs. Despite the fact CAPI operator is able to deploy the provider, it fails with errors like
```txt
2024-02-14T17:16:19.922069142Z stderr F W0214 17:16:19.921859       1 reflector.go:539] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1beta1.IPAddressClaim: the server could not find the requested resource (get ipaddressclaims.ipam.cluster.x-k8s.io)
2024-02-14T17:16:19.922109534Z stderr F E0214 17:16:19.921908       1 reflector.go:147] k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1beta1.IPAddressClaim: failed to list *v1beta1.IPAddressClaim: the server could …
```
> 🌱 Temporarily disable IPAM provider e2e test

- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/values.yaml
Makes possible to enable featureGates in InfrastructureProvider 
**Which issue(s) this PR fixes** 
Fixes #377
> ✨ Add to InfrastructureProvider spec.manager.featureGates

- internal/controller/manifests_downloader.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- test/e2e/air_gapped_test.go
- test/e2e/helpers_test.go
- test/e2e/resources/core-cluster-api-v1.5.4.yaml
- test/e2e/resources/core-cluster-api-v1.6.0.yaml
When we use configmaps as a provider source, we filter them by provided labels and then take the latest version. Unfortunately, we list configmaps in all namespaces, which is not correct.
This PR restricts the search by the provider namespace only.
Fixes #
> 🐛 Restrict configmap lookup to the provider namespace

- hack/charts/cluster-api-operator/templates/deployment.yaml
- hack/charts/cluster-api-operator/values.yaml
This PR allows to configure `env` section for operator `manager` container in the helm chart.
Fixes #420
> ✨ Add "env" section support to the helm chart

- internal/controller/manifests_downloader.go
- internal/controller/manifests_downloader_test.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- util/util.go
Clusterctl upgrade logic validates other installed providers, while performing upgrade for version compatibility. Operator stores this data in a ConfigMap to allow air-gapped support. This ensures we fetch correct configMap first, to validate version against correct metadata.yaml.
Fixes #446
> :bug: Collect correct manifest config map per provider while performing upgrade

- Makefile
- hack/charts/cluster-api-operator/values.yaml
- hack/inject-cert-manager-chart-version.sh
This PR changes the way that the cluster-api-operator chart relates to the cert-manager chart. Rather than package those downstream CRDs with the chart, we can simply dispatch in the cluster-api-operator chart the `cert-manager.installCRDs=true` value config.
So, with this PR, a simple `helm install --repo https://kubernetes-sigs.github.io/cluster-api-operator capi-operator cluster-api-operator` command will no longer include the cert-manager CRDs as part of its resource payload.
To explicitly install the cert-manager chart, including the CRDs that are delivered with the cert-manager chart, as part of the cluster-api-operator helm install, we will do:
- `helm install --repo https://kubernetes-sigs.github.io/cluster-api-operator capi-operator …
> don’t deliver cert-manager CRDs with cluster-api-operator chart

- .github/workflows/pr-dependabot.yaml
Test-infra jobs are already using 1.21 under the hood, so we can’t use go 1.20 for jobs here. This causes `dependabot_pr.yaml` to create a conflicting change in `make verify` as opposed to current main.
Fixes #
> 🌱 Use 1.21 golang version for tools

- README.md
Book is now available for the operator (xref: https://github.com/kubernetes-sigs/cluster-api-operator/issues/329), we can mention it in landing page notes for better visibility
> 📖 Add CAPI Operator book link to root README

- Makefile
Dependabot branches don’t have access to release history, `git describe` output is therefore empty. This causes `dependabot_pr.yaml` [job](https://github.com/kubernetes-sigs/cluster-api-operator/actions/runs/8375139988) to fail with the following error:
```
Error: path "/home/runner/work/cluster-api-operator/cluster-api-operator/out/package/cluster-api-operator-.tgz" not found
```
This change adds a default to some specific tag in such scenario.
Fixes #
> 🌱 Ensure dependabot branch has a default tag for make generate

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.9.1. Automatically generated by `make update-helm-repo`.
> 🌱 Update helm chart index.yaml to v0.9.1

- hack/update-helm-repo.sh
- hack/update-plugin-yaml.sh
Helm/plugin update scripts fail to run on Mac because of relative path, this PR switches to using absolute path in both update scripts
Fixes #
> 🐛 Use absolute path in update scripts

- cmd/plugin/cmd/init.go
- cmd/plugin/cmd/utils.go
This PR contains two fixes for the plugin Init operation:
- Get the latest operator version from the list of all available versions
Now we use "latest" tag, but due to recent clusterctl changes it forces to download metadata.yaml file which is not available for CAPI operator. Because of that installation fails with exceeded context deadline. To prevent this we specify a version when we create a repo object, and then pick the latest version from the list of all available versions.
- Add a short delay before deploying providers
We have to add a short delay here to ensure that the webhooks are successfully started.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …
> 🐛 Plugin Init improvements

- docs/book/README.md
- docs/book/src/00_introduction.md
- docs/book/src/04_developer/00.md
- docs/book/src/04_developer/01_version_migration/00.md
- docs/book/src/04_developer/01_version_migration/01_v1alpha1-to-v1alpha2.md
Fixes few broken reference links in the introduction page and adds instructions note on how to run and preview local changes to the book. It also creates a dedicated folder for migration guides (currently there is only one, but that will change in the future) to keep it cleaner and separated from developer guide contents.
> 📖 Improvements to book

- config/chart/kustomization.yaml
- config/chart/patches/keep-crds.yaml
- test/e2e/resources/full-chart-install.yaml
When CAPI Operator chart used as a dependency, the removal of the chart hosting the dependency causes CRDs to be removed. This happens because CRDs are generated as a part of `base` and therefore are managed by helm 3. Helm [docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource) define `keep` policy as:
> skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade or helm rollback) **would result in its deletion**
Setting this annotation should not prevent CRD upgrades, when resource is changed only.
Typically this removal happens after the main deployment is removed, and before any or all of the `*Provider` resources are removed. Provider resources has a finalizer, nothing can …
> Add helm.sh/resource-policy: keep to CRDs to prevent deletion

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.10.1. Automatically generated by `make update-helm-repo`.
> 🌱 Update helm chart index.yaml to v0.10.1

- internal/controller/preflight_checks.go
Currently we format the message incorrectly, which causes output like:
`Downgrade is not supported for provider aws%!!(MISSING)(EXTRA string=cluster-api)`
Fixes #
> 🐛 Fix unsupportedProviderDowngradeMessage message

- cmd/plugin/cmd/init.go
- cmd/plugin/cmd/init_test.go
- cmd/plugin/cmd/upgrade.go
- cmd/plugin/cmd/upgrade_plan.go
- cmd/plugin/cmd/upgrade_plan_test.go
- cmd/plugin/cmd/utils.go
This PR implements `upgrade plan` support for the plugin
Fixes #129
> ✨ Implement "upgrade plan" support

- Makefile
- hack/cert-manager.sh
This PR syncs Cert Manager version with Cluster API v1.7: https://github.com/kubernetes-sigs/cluster-api/pull/10517
Fixes #
> 🌱 Bump cert-manager version to v1.14.5

- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
This PR fixes a few edge cases that cause syntax errors in helm charts.
Fixes part of #532
> 🐛  Fix helm chart syntax errors

- docs/README.md
- docs/book/src/01_user/02_quick-start.md
- docs/book/src/02_installation/04_helm-chart-installation.md
- docs/quickstart.md
This PR adds some fixes to the helm chart install commands in the docs. It also adds some warnings regarding the `--wait` flag being required when installing providers with the helm chart.
Fixes #532
> 📖  Correct Helm chart install instructions in docs + add warnings about --wait being required

- config/manager/manager.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
- hack/charts/cluster-api-operator/templates/deployment.yaml
- test/e2e/resources/full-chart-install.yaml
> ⚠️ feat(rbac): use real ServiceAccount instead of default

- docs/README.md
- docs/book/src/03_topics/02_configuration/04_patching-provider-manifests.md
The docs refer to this field as `resourcePatches` while its actually called [`manifestPatches`](https://github.com/kubernetes-sigs/cluster-api-operator/blob/628476cec06411357f07d514dfbf0444dad40c03/api/v1alpha2/provider_types.go#L75) in the code and in the CRD.
I also fixed the indentation in the examples for this field to make sense.
> 📖 Fix manifestPatches field name

- hack/charts/cluster-api-operator/templates/infra.yaml
This PR fixes a bug where the `additionalDeployments` field was bring printed incorrectly when using a values.yaml file. The `recursivePrinter` is not needed, and we can just use `toYaml` instead.
Fixes #
> :bug: Fix infra Helm chart logic for additionalDeployments

- internal/controller/manifests_downloader_test.go
- internal/controller/phases.go
This change allows to pass `images` variable overrides to a local `clusterctl.yaml` file, allowing a granular control on default image sources for the provider installations.
Added tests for existing overrides functionality.
Fixes #
> ✨ Pass image overrides to in-memory client

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.13.0. Automatically generated by `make update-helm-repo`.
> ✨ Update index.yaml for v0.13.0 minor release

- config/crd/patches/webhook_in_addonproviders.yaml
- config/crd/patches/webhook_in_bootstrapproviders.yaml
- config/crd/patches/webhook_in_controlplaneproviders.yaml
- config/crd/patches/webhook_in_coreproviders.yaml
- config/crd/patches/webhook_in_infrastructureproviders.yaml
- config/crd/patches/webhook_in_ipamproviders.yaml
- config/crd/patches/webhook_in_runtimeextensionproviders.yaml
- test/e2e/resources/full-chart-install.yaml
This removes the invalid CABundle, required for k8s 1.31.
See https://github.com/kubernetes-sigs/cluster-api/pull/10972 for context
Fixes #590
> Remove the invalid caBundle, required for 1.31

- .github/workflows/verify.yml
- hack/verify-pr-title.sh
Verify job is failing on PRs. The solution was presented by CAPV: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3188
Fixes #
> 🌱 Verify PR titles with shell script

- internal/controller/image_overrides.go
- internal/controller/image_overrides_test.go
- internal/controller/manifests_downloader_test.go
- internal/controller/phases.go
This change allows to use mounted `clusterctl-config.yaml` file to override provider images.
```yaml
apiVersion: v1
data:
clusterctl.yaml: |
images:
control-plane-rke2:
repository: myorg.io/local-repo
tag: v9.9.9
bootstrap-rke2:
repository: myorg.io/local-repo
tag: v9.8.9
```
results in:
`image: http://myorg.io/local-repo/cluster-api-provider-rke2-controlplane:v9.9.9`
and 
`image: http://myorg.io/local-repo/cluster-api-provider-rke2-bootstrap:v9.8.9`
for `rke2` CP and Bootstrap providers.
Fixes #
> :bug: Allow to use image overrides from mounted custerctl-config.yaml file

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.14.0. Automatically generated by `make update-helm-repo`.
> 🌱 Update helm chart index.yaml to v0.14.0

- internal/controller/component_customizer.go
We prevent the providers to be scoped to a namespace. This PR remove the namespace arg check.
Fixes #624
> 🐛 Fix remove namespace arg check for provider

- hack/charts/cluster-api-operator/templates/control-plane.yaml
- hack/charts/cluster-api-operator/templates/infra-conditions.yaml
- test/e2e/helm_test.go
- test/e2e/resources/kubeadm-manager-defined.yaml
This PR adds support for specifying featureGates in the ControlPlaneProvider. This is particularly necessary when using infrastructure=docker, as we need to pass CLUSTER_TOPOLOGY=true to the kubeadm provider. Currently, there is no way to do this, and this feature is essential for enabling cluster topology features in kubeadm.
**Usage Example**:
To use this feature, you can install the capi-operator with Helm and specify the feature gates in your values file. Here is an example:
```bash
helm install capi-operator cluster-api-operator/cluster-api-operator --version 0.10.1 -n capi-operator-system --create-namespace --values ./example-values.yaml
```
`example-values.yaml`:
```yaml
cert-manager:
enabled: false
installCRDs: false
infrastructure: …
```
> :sparkles: Add featureGates to ControlPlaneProvider

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.15.0.
> 🌱 Update helm chart index.yaml to v0.15.0

- hack/charts/cluster-api-operator/templates/deployment.yaml
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/resources/full-chart-install.yaml
Remove the [deprecated and now removed](https://github.com/kubernetes-sigs/cluster-api/pull/11140) _--metrics-bind-addr_ flag from the helmchart.
**Which issue(s) this PR fixes**
Fixes #664
> 🐛 Remove metricsBindAddr from helmchart

- hack/charts/cluster-api-operator/templates/deployment.yaml
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/resources/full-chart-install.yaml
This change standardizes health check endpoint to use default port of `:9440`.
Fixes #
> 🌱 Implement healthz and readyz checks in the deployment

- test/e2e/helm_test.go
We should test our chart installation inside our e2e tests.
Fixes #667
> :bug: Perform full chart install in e2e test

- hack/charts/cluster-api-operator/templates/control-plane.yaml
Handle cases where manager values is present for other provider than the controlplaneprovider one.
This will make sure the manager field for a specific control plane provider is added only if featureGates for this one are present.
Example with current/v0.15.1 chart:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
name: kubeadm
namespace: capi-kubeadm-control-plane-system
annotations:
"helm.sh/hook": "post-install,post-upgrade"
"helm.sh/hook-weight": "2"
"argocd.argoproj.io/sync-wave": "2"
spec:
manager:
```
Fixes #
> 🐛 avoid empty manager field in ControlPlaneProvider when no features gates provided

- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/values.yaml
**What this PR does / why we need it**: This adds [fetchConfig](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-operator/operator.cluster.x-k8s.io/InfrastructureProvider/v1alpha2) to the `InfrastructureProvider`.  
This can be used like this:
```
infrastructure: "oci"
manager:
featureGates:
oci:
MachinePool: true
OKE: true
fetchConfig:
oci:
url: https://github.com/ts-mini/cluster-api-provider-oci/releases
```
The attempt was to follow the existing patterns of per-provider config, allowing users to set fetchConfigs per provider if needed.  Happy to adjust as needed!
> ✨ adding fetchConfig to InfrastructureProvider template in helmchart

- hack/charts/cluster-api-operator/templates/core.yaml
- test/e2e/helm_test.go
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-custom-versions.yaml
- test/e2e/resources/all-providers-manager-defined-no-feature-gates.yaml
- test/e2e/resources/feature-gates.yaml
- test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
**What this PR does**
In this PR, I’ve reverted MatchYAML to Equal, fixed all the broken tests. Also, I discovered and fixed a bug in the core provider specification condition.
**Why we need it**:
While working on PR [#688,](https://github.com/kubernetes-sigs/cluster-api-operator/pull/688) I’ve observed that a significant number of Helm chart e2e tests are false positives. This is because the generated YAML files in the test/e2e/resources directory do not accurately reflect the expected results from the test cases.
I believe this issue arises because `MatchYAML` is being used instead of `Equal` ([#549](https://github.com/kubernetes-sigs/cluster-api-operator/pull/549)). `MatchYAML` only compares the first YAML document within a file, as demonstrated in a quick example.
```
package …
```
> 🐛 Fix helm chart e2e tests: MatchYAML to Equal

- api/v1alpha2/provider_types.go
- internal/controller/manifests_downloader.go
- internal/controller/phases.go
As developer I'm creating Cluster API operator resources from the golang code and would like to have to utilize common project constants as much as possible to avoid mistakes and reduce number of copy/paste operation.
This PR allows to use constants for the air-gapped installation to be imported from the project API.
Fixes #
> :seedling: Make annotation and component constants public and exportable

- go.mod
- hack/chart-update/go.mod
- hack/tools/go.mod
- test/go.mod
Looks like we need to avoid using go version with patch number included in the go.mod files 
```
go: downloading sigs.k8s.io/kustomize/kustomize/v5 v5.6.0
go: sigs.k8s.io/kustomize/kustomize/v5@v5.6.0 (in sigs.k8s.io/kustomize/kustomize/v5@v5.6.0): go.mod:3: invalid go version '1.22.7': must match format 1.23
make[2]: *** [Makefile:204: /workspace/hack/tools/bin/kustomize-v5.6.0] Error 1
```
Similar issue was reported in https://github.com/siderolabs/conform/issues/251 and suggestion was to remove patch number from the version. 
Fixes #
Unfortunately, when running locally the same target (`make …
> 🌱 Use go version without the patch number in go.mod files

- cloudbuild.yaml
After a recent discussion over the slack [thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1738139430595509) the root cause for CI failures in https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-cluster-api-operator-push-images seems to be the old image used in cloudbuild which does not support go 1.23. 
This PR bumps gcb-docker-gcloud image tag in cloudbuild to latest which should support go version 1.23.x
Similar issue: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2297
Fixes #
> 🐛 Bump gcb-docker-gcloud image tag in cloudbuild

- docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
- docs/local-development.md
This PR simplifying ConfigMap with metadata configuration to be able all required modifications without additional tools like `yq` involving. All changes are done via `kubectl` utility and enough for the demonstration and configuration. 
Fixes #
> :book: Simplifying ConfigMap with metadata configuration

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.16.0.
> 🌱 Update helm chart index.yaml to v0.16.0

- Makefile
- test/e2e/README.md
This PR introduces new Makefile target with `docker-build-e2e` prerequisite target 
Fixes #141
> 🌱 Add new Makefile target to run e2e tests locally

- docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
This is small fix to the book related to the notes, how provider manifest version is selecting in ConfigMaps
Fixes #
> :book: Add info about version selection in ConfigMap to the air-gapped env

- .github/workflows/golangci-lint.yml
- .gitignore
- Makefile
- cmd/plugin/cmd/init.go
- cmd/plugin/cmd/utils.go
- test/e2e/air_gapped_test.go
- test/e2e/compressed_manifests_test.go
- test/e2e/doc.go
- test/e2e/e2e_suite_test.go
- test/e2e/helm_test.go
- test/e2e/helpers_test.go
- test/e2e/minimal_configuration_test.go
- test/framework/all_type_helpers.go
- test/framework/conditions.go
- test/framework/doc.go
This fix linter issues for the e2e test packages. Able to run `make lint` and `make lint-fix` now. 
Fixes #
> :seedling: Fix linter for the e2e test packages

- internal/controller/phases_test.go
- util/util.go
**What this PR does / why we need it**: The current implementation of the gitlab check uses HasPrefix - which doesn't allow for a gitlab whose domain could be different (gitlab-example.domain.com)
**Which issue(s) this PR fixes**:
Fixes #705
> ✨ Allow accepting self-hosted gitlab installations

- .golangci.yaml
- cmd/main.go
- go.mod
- internal/controller/consts.go
- internal/controller/coreprovider_to_providers.go
- internal/controller/coreprovider_to_providers_test.go
- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/healthcheck/suite_test.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
- internal/controller/secrets_to_providers.go
- internal/controller/secrets_to_providers_test.go
- internal/controller/suite_test.go
- internal/envtest/environment.go
This PR allows you to avoid from polling in reconcile loop every 30 seconds, and move to catching events from the CoreProvider object when Ready condition become True. We should avoid re-querying at intervals where possible.
Also, configSecret request is optimized if option is enabled. Since a cluster can have a large number of secret objects, it is a very expensive procedure to go through all the providers each time secrets are catches without an index. The number of provider objects in the cluster is small enough that the index on the name/namespace fields will not be very large.
Fixes #
> :sparkles: Handle Kubernetes events for waiting CoreProvider in preflight check

- hack/charts/cluster-api-operator/templates/ipam.yaml
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/resources/full-chart-install.yaml
This PR introduces a Helm chart template for deploying IPAMProvider.
> ✨ Add IPAM provider support to Cluster API Operator Helm chart

- Dockerfile
- Makefile
This PR allows to build operator images in a private docker registry infrastructure without having to edit the Makefile and Dockerfile. All parameters can be configured. The current parameters are left equal to the default values before.
Fixes #
> 🌱 Add ability to build operator images in a private docker registry

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.17.0.
> 🌱 Update helm chart index.yaml to v0.17.0

- internal/controller/phases.go
- test/e2e/air_gapped_test.go
- test/e2e/helpers_test.go
- test/e2e/resources/bootstrap-kubeadm-v1.7.7.yaml
- test/e2e/resources/bootstrap-kubeadm-v1.8.0.yaml
- test/e2e/resources/controlplane-kubeadm-v1.7.7.yaml
- test/e2e/resources/controlplane-kubeadm-v1.8.0.yaml
- util/util.go
When using `fetchConfig` in the [provider spec](https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/05_provider-spec-configuration.html?highlight=fetchconfig#provider-spec) for multiple providers, the operator does not properly pass information about other "custom" providers to the [clusterctl configuration](https://cluster-api.sigs.k8s.io/clusterctl/configuration#provider-repositories). Currently, the operator passes repository information about the current provider only, and the default list from `clusterctl`. This causes `clusterctl` to fail it's lagging provider check, which is intended to keep providers within a valid version skew to avoid a broken cluster, and prevents upgrading providers when using `fetchConfig` in multiple …
> 🐛: fix unknown provider errors when using fetchConfigs

- hack/charts/cluster-api-operator/templates/core-conditions.yaml
- test/e2e/helm_test.go
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-latest-versions.yaml
- test/e2e/resources/all-providers-manager-defined-no-feature-gates.yaml
- test/e2e/resources/feature-gates.yaml
- test/e2e/resources/kubeadm-manager-defined.yaml
- test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
- test/e2e/resources/only-infra-and-ipam.yaml
- test/e2e/resources/only-ipam.yaml
This PR brings e2e tests for the IPAM provider into the Cluster API Operator Helm chart, on top of what was done in PR #688.
- Update core-conditions.yaml to include IPAM provider in deployment conditions
- Add IPAM provider test cases in helm_test.go
- Create new / update test resource files for IPAM provider scenarios
> 🌱 Add e2e tests for IPAM provider to Cluster API Operator Helm chart

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.17.1.
> 🌱 Update helm chart index.yaml to v0.17.1

- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra-conditions.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/templates/ipam.yaml
- test/e2e/resources/all-providers-manager-defined-no-feature-gates.yaml
- test/e2e/resources/feature-gates.yaml
- test/e2e/resources/kubeadm-manager-defined.yaml
- test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
Following https://github.com/kubernetes-sigs/cluster-api-operator/pull/681 
Handle cases where manager values is present for default controlPlane provider.
This will make sure the manager field for the default control plane provider is added only if featureGates for this one are present when no controlPlane is provided (despite calling it out in the previous example).
The default controlPlane provider being `kubeadm`
The last part was the miss of https://github.com/kubernetes-sigs/cluster-api-operator/pull/681 
Example with current/v0.17.0 chart:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
name: kubeadm
namespace: capi-kubeadm-control-plane-system
annotations:
"helm.sh/hook": "post-install,post-upgrade" …
```
> 🐛 avoid empty manager field in ControlPlaneProvider when no controlPlane and no features gates provided

- hack/charts/cluster-api-operator/templates/addon.yaml
- hack/charts/cluster-api-operator/templates/bootstrap.yaml
- hack/charts/cluster-api-operator/templates/control-plane.yaml
- hack/charts/cluster-api-operator/templates/core-conditions.yaml
- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra-conditions.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/templates/ipam.yaml
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-custom-versions.yaml
- test/e2e/resources/all-providers-latest-versions.yaml
- test/e2e/resources/all-providers-manager-defined-no-feature-gates.yaml
- test/e2e/resources/feature-gates.yaml
- test/e2e/resources/kubeadm-manager-defined.yaml
- test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
- test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
- test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
- test/e2e/resources/multiple-infra-custom-ns-versions.yaml
- test/e2e/resources/only-addon.yaml
- test/e2e/resources/only-bootstrap.yaml
- test/e2e/resources/only-control-plane.yaml
- test/e2e/resources/only-infra-and-addon.yaml
- test/e2e/resources/only-infra-and-ipam.yaml
- test/e2e/resources/only-infra.yaml
- test/e2e/resources/only-ipam.yaml
Allow to disable have helm hooks. This help with argocd resource management (cannot autosync, no proper tracking of resources on deletion) and avoid deleting all hook resources each time we need to sync. This can be scary if the un-install does not work as expected and stuck the app state with no provider running.
Argocd automatically convert hooks from helm and there is no way to avoid that once those are set the resource will be considered deployed by a hook.
For reference here is the conversion: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks
By enabling the removal of helm hooks, argocd will still install the resource in the right order using the phase only ( https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how …
> 🐛  Improve deployment with Argocd by allowing to remove helm hooks 

- Makefile
- cmd/plugin/cmd/suite_test.go
- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/phases.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
- test/e2e/air_gapped_test.go
> :bug: InfrastructureProvider waiting for core provider even though CoreProvider is ready

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.18.0.
> 🌱 Update helm chart index.yaml to v0.18.0

- internal/controller/coreprovider_to_providers.go
- internal/controller/genericprovider_controller.go
- internal/controller/genericprovider_controller_test.go
- internal/controller/secrets_to_providers.go
Added fix and test for it, as this case (create not Ready CoreProvider before or after other providers) never been tested.
Fixes #755
> :bug: Fix appliedSpecHashAnnotation set if PreflightCheckPassed is not True

- api/v1alpha2/conditions_consts.go
- test/e2e/air_gapped_test.go
- test/e2e/compressed_manifests_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/helm_test.go
- test/e2e/helpers_test.go
- test/e2e/minimal_configuration_test.go
- test/framework/conditions.go
`HaveStatusCondition` -> `HaveStatusConditionsTrue` function refactored to be able accept multiple conditions simulteniuosly
test/e2e/air_gapped_test.go refactored, each It is independent now.
Fixes #757
> :seedling: Add more condition validations for providers in e2e tests

- hack/charts/cluster-api-operator/templates/addon.yaml
- hack/charts/cluster-api-operator/templates/bootstrap.yaml
- hack/charts/cluster-api-operator/templates/control-plane.yaml
- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/templates/ipam.yaml
- hack/charts/cluster-api-operator/values.schema.json
- hack/charts/cluster-api-operator/values.yaml
- test/e2e/helm_test.go
- test/e2e/resources/multiple-infra-custom-ns-versions.yaml
When deploying clusters to AKS using Workload Identity [an annotation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#create-a-kubernetes-service-account) is required on the service account and [a label](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#deploy-your-application) is required on the pod. By extending the chart to expose the [already existing functionality to patch provider manifests](https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/04_patching-provider-manifests) this PR allows for setting up AKS clusters using Workload Identity.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> ⚠️ Make helm chart values extensible per component

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.19.0.
> 🌱 Update helm chart index.yaml to v0.19.0

- internal/controller/component_customizer.go
- internal/controller/component_customizer_test.go
> :bug: CAPI operator incorrectly finds the manager container if the number of containers is greater than one

- api/v1alpha2/controllermanagerconfig_types.go
- config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
- test/e2e/resources/full-chart-install.yaml
Mini spelling fix for the description of the controller metrics configuration.
> 🌱 Fix spelling in controller metrics config description

- cmd/main.go
- config/manager/manager.yaml
- hack/charts/cluster-api-operator/values.yaml
- internal/controller/phases.go
- internal/controller/phases_test.go
- test/e2e/resources/full-chart-install.yaml
This PR slightly improves memory footprint of the operator by implementing minor adjustments to the code:
- Skip components.yaml caching in upgrade scenario for all other providers except upgraded. Only metadata.yaml is important there.
- Pass concurrency number to the manager instance, allowing max X concurrent reconciles across different providers.
- Increases memory limits to 300Mi from 150Mi, since in current setup azure provider alone is able to bump memory usage to median of ~130Mi.
Fixes #
> 🌱 Pass global concurrency number to manager

- hack/charts/cluster-api-operator/templates/ipam.yaml
While attempting to perform an air-gapped installation of the cluster-api operator using in-cluster IPAM, the helm chart does not utilize fetchConfig for the IPAMProvider CR, so there isn't a way to point the IPAM container to anything other than registry.k8s.io/capi-ipam-ic/cluster-api-ipam-in-cluster-controller:v1.0.1. Since I am trying to point all containers towards a local registry, I need to have the IPAMProvider fetch a LAN-located config which will point towards the disconnected container registry instead of generating its own. The IPAMProvider CRD already supports this, it just needs an update to the Helm chart to allow it to work properly.
Basically extending these steps:
https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/0 …
> ✨ add fetchConfig support to IPAMProvider in chart

- internal/controller/oci_source.go
- internal/controller/oci_source_parse_test.go
Previously, an OCI source "registry:port/image" would consider ":port/image" as the tag
Add unit tests to verify change works as desired, and prevent regressions in the future
Did not create an issue to go with this PR, happy to do so if requested by the maintainers
>  🐛 Fix OCI source parsing issues

- hack/charts/cluster-api-operator/values.yaml
I had a hard time while figuring out how to configure the feature-gates for providers in the helm-chart. I thought it would work like for core - so i tried `manager.featureGates.infrastructure`.
This PR adds a little example on how to get feature-gates working.
> 🌱 Add examples for feature-gates in helm chart values.yaml

- cmd/main.go
- controller/alias.go
- internal/controller/genericprovider_controller.go
- internal/controller/manifests_downloader.go
- internal/controller/manifests_downloader_test.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/controller/suite_test.go
This PR refactors the generic provider reconciliation logic to expose internal controllers and phases through the `controller/alias.go` file. This change allows external users to construct and interact with the core controller logic outside the operator pod.
- Introduce and expose a phase-based framework for generic provider reconciliation.
- Define and expose a custom `Result` type to avoid controller-runtime dependency on import.
- Enable selectable watching of CoreProvider changes for non-core provider types.
Fixes #798
> ✨ Expose internal controllers

- docs/quickstart.md
- test/e2e/helm_test.go
This PR removes all references to the deprecated `cert-manager.enabled` parameter from the codebase. 
Starting with v0.11.0, the Helm chart no longer includes cert-manager as a dependency, making these parameters ineffective. This cleanup ensures our documentation and tests reflect the current state of the project.
Fixes #(issue number if applicable)
The `cert-manager.enabled` parameter and related settings were removed from the Helm chart dependencies in v0.11.0 (released June 2024). These parameters have been non-functional since then, so their removal has no impact on functionality.
> 🌱 Remove deprecated cert-manager.enabled parameter references

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.21.0.
Automatically generated by `make update-helm-plugin-repo`.
> 🌱 Update helm chart index.yaml to v0.21.0

- api/v1alpha2/addonprovider_wrapper.go
- api/v1alpha2/bootstrapprovider_wrapper.go
- api/v1alpha2/controlplaneprovider_wrapper.go
- api/v1alpha2/coreprovider_wrapper.go
- api/v1alpha2/genericprovider_interfaces.go
- api/v1alpha2/infrastructureprovider_wrapper.go
- api/v1alpha2/ipamprovider_wrapper.go
- api/v1alpha2/runtimeextensionprovider_wrapper.go
- cmd/plugin/cmd/init_test.go
- cmd/plugin/cmd/preload.go
- cmd/plugin/cmd/upgrade_plan.go
- cmd/plugin/cmd/upgrade_plan_test.go
- controller/alias.go
- internal/controller/client_proxy.go
- internal/controller/genericprovider_controller.go
- internal/controller/manifests_downloader_test.go
- internal/controller/oci_source.go
- internal/controller/phases.go
- internal/controller/phases_test.go
- internal/controller/preflight_checks.go
- internal/controller/preflight_checks_test.go
- util/util.go
CAPI Operator reconciles essentially 2 provider types: Core and non-Core providers. There are differences in `GetType()` method and how each provider translates to the path to the component files in the release payload, but these details are abstracted away behind `GenericProvider` interface.
This change exposes inner methods used to determine provider type and provide a `clusterctl` equivalent for it via a set of injection points, available as a public API through `alias.go`
Fixes #
> ✨ Expose clusterctl provider dependent logic for custom provider building

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.22.0.
Automatically generated by `make update-helm-plugin-repo`.
> 🌱 Update helm chart index.yaml to v0.22.0

- api/v1alpha2/controlplaneprovider_wrapper.go
Normalize provider type name for controlPlane, both kubeadm and rke2 contolPlane components have name control-plane-components.yaml
Issue: https://github.com/kubernetes-sigs/cluster-api-operator/issues/858
Fixes #
> 🐛 [OCI] Normalize provider type name when control plane

- controller/alias.go
- internal/controller/phases.go
With the recent changes in CAPI Operator that expose phase reconciliation, it would be great if we can also make applying changes on provider manifest definition easier during one of these phases.
This change introduces a new field in `PhaseReconciler` to embed one/multiple [ComponentsAlterFn](https://github.com/kubernetes-sigs/cluster-api/blob/7782ab73d31d3e1ffe3c46966bd438efe592be72/cmd/clusterctl/client/repository/components.go#L149) that are applied on `Fetch`. With this solution, specific components on a provider's manifest definition can be patched based on the logic passed in this/these function/functions.
Additionally, this adds an extra commit to fix a typo in one of the struct names `PhaseReconcilerOption`. **Looks like this is the reason …
> :sparkles: Support alter components custom func

- hack/charts/cluster-api-operator/templates/_helpers.tpl
- hack/charts/cluster-api-operator/templates/addon.yaml
- hack/charts/cluster-api-operator/templates/bootstrap.yaml
- hack/charts/cluster-api-operator/templates/control-plane.yaml
- hack/charts/cluster-api-operator/templates/core.yaml
- hack/charts/cluster-api-operator/templates/infra.yaml
- hack/charts/cluster-api-operator/templates/ipam.yaml
- hack/charts/cluster-api-operator/values.schema.json
- test/e2e/resources/all-providers-custom-ns-versions.yaml
- test/e2e/resources/all-providers-custom-versions.yaml
- test/e2e/resources/all-providers-latest-versions.yaml
- test/e2e/resources/all-providers-manager-defined-no-feature-gates.yaml
- test/e2e/resources/feature-gates.yaml
- test/e2e/resources/only-addon.yaml
- test/e2e/resources/only-infra-and-addon.yaml
This builds on the extensibility introduced in #638.
* This makes the connection between the `configSecret` and the component/provider using said config clearer.
* Reduces duplication of the `configSecret` logic across templates by moving it into a helper.
* Adds the ability to configure `fetchConfig`.
This has been implemented in such a way that it is backwards compatible and will default to the existing behaviour. If you want to use the new behaviour you would have to do something like this:
```yaml
core:
cluster-api:
version: v1.9.6
configSecret:
name: my-custom-core-config
namespace: capi-system
infrastructure:
azure:
namespace: capz-system
version: v1.19.1
configSecret:
name: azure-variables
namespace: capz-system
```
while also removing the …
> :sparkles: Make configSecret configurable per component

- docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
This PR adds a few notes to the air-gapped-environment documentation that add clarity to properly configuring the oci artifacts to be fetched.
I was recently setting up an air-gapped installation of the operator and installing providers to my cluster following these docs and found that it was ambiguous on how to configure the artifacts. I was under the impression that the artifacts need only to be in an oci compliant registry rather than the oci layout. As such, I was building simple docker images that were not in oci layout and the operator could not find the metadata/components files for any given provider despite successfully fetching the artifact from the oci registry.
The added notes include a link to the local plugin docs describing how to …
> 📖 add notes on building oci artifacts as well as using plain http

- internal/controller/genericprovider_controller.go
🐛 Update existing conditions to have a non-empty Reason field
This PR fixes a bug where existing Kubernetes conditions could have empty `Reason` fields, which violates the Kubernetes API specification brought in https://github.com/kubernetes-sigs/cluster-api-operator/pull/880. The Kubernetes condition API requires that all conditions must have a non-empty `Reason` field.
The fix adds a `normalizeExistingConditions` function that:
- Checks all existing conditions on provider objects during reconciliation
- Sets the `Reason` field to the condition type name if it's empty
Fixes #
> 🐛 Update existing conditions to have a non-empty Reason field

- api/v1alpha2/controllermanagerconfig_types.go
- config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
- config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
- internal/controller/component_customizer.go
- test/e2e/resources/full-chart-install.yaml
This PR adds the fields `DiagnosticsAddress` and `InsecureDiagnostics` to `ControllerMetrics` struct. It also configures these fields as flags in the deployment.
As of CAPI v1.9, the flag `--metrics-bind-addr` was removed, so the flag `--diagnostics-address` must be used in place.
> ✨ Implement diagnostics fields in Providers CRD

- index.yaml
- plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.24.0.
Automatically generated by `make update-helm-plugin-repo`.
> 🌱 Update helm chart index.yaml to v0.24.0
