.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/verify.yml
Add PR template, 2 issue templates, and a GH workflow to verify PR content. https://github.com/kubernetes-sigs/cluster-api/tree/main/.github
=> Add github templates

Makefile, scripts/ci-apidiff.sh
Fix CI script for apidiff, now it's similar to https://github.com/kubernetes-sigs/cluster-api/blob/main/scripts/ci-apidiff.sh
Fixes #
=> 🐛 Fix apidiff ci job

docs/capi-operator-proposal.md
Add a copy of the original proposal https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20201020-capi-provider-operator.md, it will be much easier to keep it updated if the proposal is kept in this repo.
Fixes #
=> ✨ Add original copy of operator proposal

controllers/genericprovider_controller.go, controllers/phases.go
observedGeneration should not block reconciliation if it wasn't changed
Fixes #
=> ✨ Refactor observedGeneration

README.md
Add basic readme
Fixes https://github.com/kubernetes-sigs/cluster-api-operator/issues/5
=> ✨ Add basic readme

hack/ensure-kustomize.sh
This PR helps in fixing make file kustomize task
Fixes #24
=> :bug: Added file to download kustomize

Makefile, api/v1alpha1/conditions_consts.go, api/v1alpha1/provider_types.go, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_bootstrapproviders.yaml, config/crd/patches/cainjection_in_controlplaneproviders.yaml, config/crd/patches/cainjection_in_coreproviders.yaml, config/crd/patches/cainjection_in_infrastructureproviders.yaml, config/crd/patches/webhook_in_bootstrapproviders.yaml, config/crd/patches/webhook_in_controlplaneproviders.yaml, config/crd/patches/webhook_in_coreproviders.yaml, config/crd/patches/webhook_in_infrastructureproviders.yaml, config/default/kustomization.yaml, config/default/kustomizeconfig.yaml, config/default/webhookcainjection_patch.yaml, config/webhook/manifests.yaml, main.go, test/e2e/e2e_suite_test.go, webhook/bootstrapprovider_webhook.go, webhook/controlplaneprovider_webhook.go, webhook/coreprovider_webhook.go, webhook/infrastructureprovider_webhook.go
=> :sparkles:Added initial validation Webhook for all the resources

OWNERS, OWNERS_ALIASES
Remove alexander-demichev from owners
Remove @alexander-demichev from owners
Fixes #
=> 🌱Update owners

OWNERS_ALIASES
Alex was an owner of the project some time ago. Glad to see him back! 
Github: https://github.com/alexander-demicev
=> 🌱 Add alexander-demicev to OWNERS

.github/dependabot.yml
This PR adds dependabot config so we can automate dependency update and run it weekly. It also ignores CAPI and Kubernetes dependencies because we want to update them manually.
Fixes #
=> 🌱 Add dependabot config

.github/dependabot.yml
We forgot to make dependabot ignore CAPI test package
Fixes #
=> 🌱 Make dependabot ignore CAPI test

README.md
Add a note to readme that project is in development and people should be careful using it.
Fixes #
=> 🌱 Add a development note to readme

internal/controllers/genericprovider_controller.go, internal/controllers/phases.go, internal/controllers/preflight_checks.go
This PR improves logging and enables more logs by default
Fixes #
=> 🌱 Make logging more consistent

internal/controllers/phases.go
This PR removes the installation of clusterctl CRDs. They are unnecessary for us, clusterctl CRs are used to store information about installed providers, and the operator does it using its own API.
Fixes #
=> ✨Remove clusterctl crds installation

Makefile, Tiltfile, cloudbuild.yaml, config/default/manager_image_patch.yaml, scripts/ci-e2e.sh
Add all required tasks for creating a release
Fixes #
=> ✨Add release make tasks

docs/getting-started.md
Add getting started docs
Fixes #
=> 📖 Add getting started docs

Makefile
Add make task for publishing docker manifests
Fixes #
=> 🌱 Add make task for publishing docker manifests

Makefile
=> 🌱 Install kustomize when releasing manifests

OWNERS, OWNERS_ALIASES
Add https://github.com/damdo to approvers.
=> 🌱 Update OWNERS

docs/capi-operator-proposal.md
the yaml was crashing due to being malformed
Fixes #
=> 📖 Update capi-operator-proposal.md

Makefile, docs/release.md, hack/get-project-maintainers.sh
Add doc describing release process and image promotion make task.
Fixes #
=> 📖 Add doc describing release process

Makefile
=> 🐛 Make release tag argument configurable

test/e2e/e2e_suite_test.go, test/e2e/helpers.go, test/e2e/minimal_configuration.go
This PR contains some small fixes and improvements for e2e tests
=> 🌱 some e2e improvements

config/chart/manager_auth_proxy_patch.yaml, config/default/manager_auth_proxy_patch.yaml
Currently we use an outdated version of kube-rbac-proxy and don't specify resources requests and limits for it.
This PR bumps kube-rbac-proxy to the latest stable version and updates manifests based on the related recommendations.
=> 🌱 Bump kube-rbac-proxy

docs/capi-operator-proposal.md
Fixes a typo in `capi-operator-proposal.md`
**Which issue(s) this PR fixes**:
Fixes #138
=> 📖 Fix typo in capi-operator-proposal.md

docs/README.md, internal/controller/preflight_checks.go
This PR adds documentation for new features we added after 0.3.0 release. Also it fixes some discrepancies and updates the TOC.
Fixes #
=> 🌱 update docs for 0.4.0 release

index.yaml
This PR updates index.yaml file for v0.4.0 release.
Fixes #
=> 🌱 Update helm chart index.yaml

.golangci.yaml, internal/controller/component_customizer.go, internal/controller/component_customizer_test.go
We temporarily disabled this linter, so it's time to enable it again.
This PR fixes issues reported by the linter. Additionally it verifies that "manager" container exists in provider deployment, and if it doesn't - operator reports an error.
Fixes #
=> 🌱 Enable nestif linter again

docs/README.md
=> 📖 update docs for v0.5.0 release

docs/release.md
Documents all the steps to create new release branch jobs after we branch out to new release branch in the repo
Related to: https://github.com/kubernetes/test-infra/pull/30372
=> 📖Document setting up new release branch jobs in release.md

index.yaml
This PR updates index.yaml for v0.5.1. Automatically generated by `make update-helm-repo`.
Fixes #
=> 🌱 Update index.yaml for v0.5.1

docs/README.md
Fixing minor typos in `README.md`, providing sensible default timeout value for installation with dependencies and multiple providers.
Fixes #
=> :book: Fix typo in helm command README, add recommended timeout value

go.mod, go.sum, internal/controller/suite_test.go, internal/envtest/environment.go
This test is empty and doesn't check anything, but requires ginkgo support.
Fixes #
=> 🌱 Remove TestAPIs from internal/controller

api/v1alpha2/addonprovider_types.go, api/v1alpha2/bootstrapprovider_types.go, api/v1alpha2/controlplaneprovider_types.go, api/v1alpha2/coreprovider_types.go, api/v1alpha2/groupversion_info.go, api/v1alpha2/infrastructureprovider_types.go, api/v1alpha2/zz_generated.deepcopy.go
To remove controller-runtime dependency from our API package, we replace its "scheme" package with apimachinery's runtime.
Fixes #
=> 🌱 Use apimachinery runtime to register API scheme

config/default/manager_auth_proxy_patch.yaml, hack/charts/cluster-api-operator/values.yaml, test/e2e/resources/full-chart-install.yaml
=> :sparkles: Allow running operator on ppc64le arch

index.yaml
=> ✨ Update helm chart repo index

internal/controller/healthcheck/healthcheck_controller.go
Improve predicate logic to prevent health checks from reconciling deployments which are not owned by a specific provider.
Fixes #
=> 🌱 Refactor healthcheck to reconcile  only owned deployments

docs/release.md
This PR aims to clarify some steps in the release process and fix several typos.
Fixes #
=> 📖 Update release docs

api/v1alpha2/addonprovider_types.go, api/v1alpha2/bootstrapprovider_types.go, api/v1alpha2/controlplaneprovider_types.go, api/v1alpha2/coreprovider_types.go, api/v1alpha2/infrastructureprovider_types.go, api/v1alpha2/ipamprovider_types.go, config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml, test/e2e/resources/full-chart-install.yaml
=> ⚠️ Add short names for custom resources

.goreleaser.yaml
- for version subcommand. 
- validated using `goreleaser release --snapshot` 
Fixes #398
=> 🌱 udpate goreleaser config to include ldflags

api/v1alpha1/bootstrapprovider_types.go, api/v1alpha1/controlplaneprovider_types.go, api/v1alpha1/coreprovider_types.go, api/v1alpha1/infrastructureprovider_types.go, config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml, config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml, test/e2e/resources/full-chart-install.yaml
=> ⚠️ Deprecate v1alpha1

Makefile
Use https by default while using `make promote-images`, to prevent issues with ssh based git cli interaction.
Fixes #
=> 🌱 Update kpromo version and set --use-ssh=false by default

OWNERS_ALIASES
I'm no longer able to commit to helping maintain this project, so I should be removed from the owners to help guide folks to active maintainers.
/area owners
=> 🌱 Drop myself from owners

index.yaml, plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.9.2. Automatically generated by `make update-helm-repo`.
Fixes #
=> 🌱 Update helm chart index.yaml to v0.9.2

hack/charts/cluster-api-operator/templates/deployment.yaml, test/e2e/resources/full-chart-install.yaml
Exposes metrics port in operator deployment
Fixes #490
=> ✨ expose metrics port in operator deployment

hack/charts/cluster-api-operator/templates/addon.yaml, hack/charts/cluster-api-operator/templates/core.yaml, hack/charts/cluster-api-operator/templates/infra-conditions.yaml, hack/charts/cluster-api-operator/templates/infra.yaml, test/e2e/resources/all-providers-custom-ns-versions.yaml, test/e2e/resources/all-providers-custom-versions.yaml, test/e2e/resources/all-providers-latest-versions.yaml, test/e2e/resources/feature-gates.yaml, test/e2e/resources/multiple-infra-custom-ns-versions.yaml, test/e2e/resources/only-addon.yaml, test/e2e/resources/only-infra-and-addon.yaml, test/e2e/resources/only-infra.yaml
This PR adds the `argocd.argoproj.io/sync-wave` annotations to CAPI Operator resources in the helm chart. It's functionally similar to helm's hook weight annotation.
Fixes #
=> 🌱  Add sync-wave annotations

index.yaml, plugins/clusterctl-operator.yaml
=> ✨Update index.yaml for v0.11.0

test/e2e/helm_test.go, test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
This PR adds a few test cases that would've caught the issues found in #532. It also switches the yaml comparison from `Equal` to `MatchYAML` which prints a much more informative message for failures.
Fixes #
=> 🌱  Add more cases to helm test

hack/charts/cluster-api-operator/templates/addon.yaml, hack/charts/cluster-api-operator/templates/bootstrap.yaml, hack/charts/cluster-api-operator/templates/control-plane.yaml, hack/charts/cluster-api-operator/templates/core-conditions.yaml, hack/charts/cluster-api-operator/templates/core.yaml, hack/charts/cluster-api-operator/templates/infra-conditions.yaml, hack/charts/cluster-api-operator/templates/infra.yaml, test/e2e/resources/all-providers-custom-ns-versions.yaml, test/e2e/resources/all-providers-custom-versions.yaml, test/e2e/resources/all-providers-latest-versions.yaml, test/e2e/resources/feature-gates.yaml, test/e2e/resources/manager-defined-missing-other-infra-spec.yaml, test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml, test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml, test/e2e/resources/multiple-infra-custom-ns-versions.yaml, test/e2e/resources/only-addon.yaml, test/e2e/resources/only-bootstrap.yaml, test/e2e/resources/only-control-plane.yaml, test/e2e/resources/only-infra-and-addon.yaml, test/e2e/resources/only-infra.yaml
**What this PR does / why we need it**: Added the ability to Installing/updating providers resources and ns's after the Helm chart has already been installed.
Fixes #
=> :seedling: Add additional hook post-upgrade

index.yaml, plugins/clusterctl-operator.yaml
Automatically generated by `make update-helm-plugin-repo`
=> 🌱 Update helm chart index.yaml to v0.15.1

internal/controller/manifests_downloader.go
The current code puts the OCI Artifact URL into a label without consideration for the allowed length of label values, this PR will set the Source label to `oci` and add the OCI URL as an annotation on the ConfigMap.
Fixes #720
=> :bug: ConfigMap OCI Image Label Error

docs/README.md, docs/book/src/01_user/02_quick-start.md, docs/book/src/02_installation/04_helm-chart-installation.md, docs/quickstart.md
The docs changes were missed in #638 and later requested by @furkatgofurov7 [here](https://github.com/kubernetes-sigs/cluster-api-operator/pull/638#issuecomment-2829735611).
Fixes #788
=> :book: fix helm install instructions

cmd/main.go, config/manager/manager.yaml, docs/book/src/04_developer/03_profiling.md, hack/charts/cluster-api-operator/templates/deployment.yaml, hack/charts/cluster-api-operator/values.yaml, test/e2e/resources/full-chart-install.yaml
=> ✨ Enable profiling for operator pod

index.yaml, plugins/clusterctl-operator.yaml
This PR updates index.yaml for v0.23.0. Automatically generated by `make update-helm-plugin-repo`.
Fixes #881
=> 🌱  Update index.yaml for v0.23.0 release
